language: cpp
sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - libboost-all-dev
      - libfftw3-dev
      - libfltk1.3-dev
      - libfplll-dev
      - libmpfr-dev
      - libpng++-dev
      - libxinerama-dev
      - libyaml-cpp-dev
      - ninja-build

script:
  - export CC=gcc-5
  - export CXX=g++-5
  - mkdir build
  - cd build
  - cmake .. -G Ninja
  - ninja
